Updates workflows

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,7 +23,7 @@ env:
   IMAGE_NAME: ${{ github.repository }}
   # Pre-set NAMESPACE_PREFIX from a GitHub variable if available
   NAMESPACE_PREFIX: ${{ vars.NAMESPACE_PREFIX }}
-  
+
 jobs:
   deploy:
     runs-on: ubuntu-latest
@@ -38,17 +38,17 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
-    
+
       - uses: kenchan0130/actions-system-info@master
         id: system-info
-    
+
       - name: Cache kubectl
         id: cache-kubectl
         uses: actions/cache@v3
         with:
           path: /usr/local/bin/kubectl
           key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-kubectl
-      
+
       - name: Install kubectl
         run: |
           if [ -z "${{ steps.cache-kubectl.outputs.cache-hit }}" ]; then
@@ -65,7 +65,7 @@ jobs:
         with:
           path: /usr/local/bin/kubeval
           key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-kubeval
-          
+
       - name: Install kubeval
         run: |
           if [ -z "${{ steps.cache-kubeval.outputs.cache-hit }}" ]; then
@@ -76,20 +76,25 @@ jobs:
           else
             echo "Using cached kubeval"
           fi
-          
+
       - id: lowercase-fully-qualified-image-name
         name: Lowercase fully qualified image name
         uses: ASzc/change-string-case-action@v2
         with:
           string: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
-     
+
       - name: Cache vendor directory
+        id: cache-vendor
         uses: actions/cache@v3
         with:
           path: vendor
-          key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-vendor-${{ hashFiles('composer.lock') }}
+          key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-vendor-${{ hashFiles('**/composer.lock') }}
+
       - name: run devsetup composer install
+        # if: steps.cache-vendor.outputs.cache-hit != 'true' # Skip if cache hit
         run: |
+          ls -la
+          test -d vendor && ls -la vendor/
           if [ -d vendor/krankikom ]; then
             echo "vendor/krankikom exists, skipping composer install"
           else
@@ -108,21 +113,38 @@ jobs:
             echo "Using existing NAMESPACE_PREFIX: ${NAMESPACE_PREFIX}"
           fi
 
-      - name: Set K8s Context
+      - name: Generate KUBECONFIG
         run: |
-          if [[ -n "${{ vars.K8S_CONTEXT }}" ]]; then
-            CONTEXT="${{ vars.K8S_CONTEXT }}"
-          elif [[ "${{ inputs.environment }}" == "production" ]]; then
-            CONTEXT="m-k8s-production"
-          else
-            CONTEXT="m-k8s-dev"
+          echo "Creating KUBECONFIG"
+          export KUBECONFIG="$HOME/kubeconfig"
+          touch $HOME/kubeconfig
+          kubectl config set-cluster default --server=${KUBERNETES_URL}
+          kubectl config set-credentials github-actions-sa --token=${KUBERNETES_TOKEN}
+          kubectl config set-context default --user=github-actions-sa --cluster=default --namespace=${NAMESPACE}
+          kubectl config use-context default
+          echo "Testing KUBECONFIG"
+          kubectl version || echo "ERROR: Somethings wrong with your VAR / Secret variables, env-secret KUBERNETES_TOKEN and repo-variable KUBERNETES_URL is set."
+          echo "KUBECONFIG=$HOME/kubeconfig" >> "$GITHUB_ENV"
+        env:
+          KUBERNETES_TOKEN: ${{ secrets.KUBERNETES_TOKEN }}
+          KUBERNETES_URL: ${{ vars.KUBERNETES_URL }}
+
+      - name: Create docker config for ImagePullSecret
+        run: |
+          echo "Creating Docker Config"
+          if [[ -d "./kubernetes/secrets" ]]; then
+            if [[ -z "${GHCR_TOKEN}" ]]; then
+              echo "ERROR: Secret 'GHCR_TOKEN' missing in Settings"
+              exit 1
+            fi
+            export DOCKER_CONFIG="./kubernetes/secrets"
+            echo $GHCR_TOKEN | docker login ghcr.io -u '$' --password-stdin
           fi
-          echo "K8S_CONTEXT=$CONTEXT" >> $GITHUB_ENV
+        env:
+          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
 
       - name: Kustomize and kubectl apply
         run: |
-          export KUBECONFIG="$PWD/kubeconfig"
-          echo "$KUBECFGSECRET" >"$KUBECONFIG"
           cd "kubernetes/$ENVIRONMENT"
           ls -al
           echo ""
@@ -142,17 +164,17 @@ jobs:
           kustomize build | kubeval --ignore-missing-schemas --strict --force-color
           echo "---------------------------------"
           echo "Deleting pimcore-migration Job (so we can recreate it) ... a failure is not a problem:"
-          kubectl -n "${NAMESPACE_PREFIX}-${ENVIRONMENT}" --context="${K8S_CONTEXT}" delete job pimcore-migration || true
+          kubectl -n "${NAMESPACE_PREFIX}-${ENVIRONMENT}" delete job pimcore-migration || true
           echo "---------------------------------"
           echo "Running kubectl apply"
-          kustomize build | kubectl --context="${K8S_CONTEXT}" apply -f -
+          kustomize build | kubectl apply -n "${NAMESPACE_PREFIX}-${ENVIRONMENT}" -f -
           echo "---------------------------------"
           echo "PIMCORE_INSTALL: $PIMCORE_INSTALL"
           if [ "$PIMCORE_INSTALL" != "false" ]; then
             echo "Running pimcore install"
             cd pimcore-install
             echo "Deleting pimcore-install Job (so we can recreate it) ... a failure is not a problem:"
-            kubectl -n "${NAMESPACE_PREFIX}-${ENVIRONMENT}" --context="${K8S_CONTEXT}" delete job pimcore-install || true
+            kubectl -n "${NAMESPACE_PREFIX}-${ENVIRONMENT}" delete job pimcore-install || true
             echo "Setting image version (php-fpm)"
             kustomize edit set image "k-registry.krankikom.de/krankikom/pimcore-website=${FULL_IMAGENAME_LOWER}:${IMAGELABEL}"
             echo "Setting namespace ${NAMESPACE_PREFIX}-${ENVIRONMENT}"
@@ -162,7 +184,7 @@ jobs:
             echo "Running kubeval"
             kustomize build | kubeval --ignore-missing-schemas --strict --force-color
             echo "Running kubectl apply"
-            kustomize build | kubectl --context="${K8S_CONTEXT}" apply -f -
+            kustomize build | kubectl apply -n "${NAMESPACE_PREFIX}-${ENVIRONMENT}" -f -
             cd ..
           fi
         env:
@@ -171,3 +193,4 @@ jobs:
           IMAGELABEL: ${{ inputs.imagelabel }}
           PIMCORE_INSTALL: ${{ inputs.pimcore_install }}
           KUBECFGSECRET: ${{ secrets.KUBECONFIG }}
+          DOCKERJSON: ${{ secrets.DOCKERJSON }}
