Updated docker build with caching

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -36,10 +36,18 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
+      
+      - uses: kenchan0130/actions-system-info@master
+        id: system-info
 
-      - name: run devsetup bootstrap
+      - name: Cache vendor directory
+        uses: actions/cache@v2
+        with:
+          path: vendor
+          key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-vendor-${{ hashFiles('composer.lock') }}
+      - name: run devsetup composer install
         run: |          
-          ./devsetup-bootstrap.sh
+          ./devsetup-composer-install.sh
 
       - name: Setup Docker buildx
         uses: docker/setup-buildx-action@312f67c6629946ba17269558b63d0bd84a63caab
@@ -110,25 +118,30 @@ jobs:
       # with sigstore/fulcio when running outside of PRs.
       id-token: write
     
-    services:
-      mariadb:
-        image: mariadb:10.5.17
-        ports:
-          - 3306
-        env:
-          MYSQL_USER: pimcore
-          MYSQL_PASSWORD: pimcore
-          MYSQL_DATABASE: pimcore
-          MYSQL_ROOT_PASSWORD: pimcore1
-        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
+    #services:
+    #  mariadb:
+    #    image: mariadb:10.5.17
+    #    ports:
+    #      - 3306
+    #    env:
+    #      MYSQL_USER: pimcore
+    #      MYSQL_PASSWORD: pimcore
+    #      MYSQL_DATABASE: pimcore
+    #      MYSQL_ROOT_PASSWORD: pimcore1
+    #    options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
 
-      - name: run devsetup bootstrap
+      - name: Cache vendor directory
+        uses: actions/cache@v2
+        with:
+          path: vendor
+          key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-vendor-${{ hashFiles('composer.lock') }}
+      - name: run devsetup composer install
         run: |          
-          ./devsetup-bootstrap.sh
+          ./devsetup-composer-install.sh
 
       # Workaround: https://github.com/docker/build-push-action/issues/461
       - name: Setup Docker buildx
@@ -162,14 +175,14 @@ jobs:
         with:
           string: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-apache
 
-      - name: Verify MariaDB connection
-        env:
-          PORT: ${{ job.services.mariadb.ports['3306'] }}
-        run: |
-          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
-            echo "Waiting for mariadb"
-            sleep 1
-          done         
+      #- name: Verify MariaDB connection
+      #  env:
+      #    PORT: ${{ job.services.mariadb.ports['3306'] }}
+      #  run: |
+      #    while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
+      #      echo "Waiting for mariadb"
+      #      sleep 1
+      #    done         
 
       # Build and push Docker image with Buildx (don't push on PR)
       # https://github.com/docker/build-push-action
